SELECT ?meter ?uuid ?key ?query ?version
WHERE {
    ?meter rdf:type/rdfs:subClassOf* brick:Power_Meter .
    ?meter bd:hasData ?point .
    ?point bd:hasArchiver ?archiver .
    
    ?point bd:uuid ?uuid .
    ?point bd:key  ?key .
    
    ?archiver bd:query   ?query .
    ?archiver bd:version ?version .
}

