SELECT DISTINCT ?meter ?room ?uuid ?key ?query ?version
WHERE {
    ?meter rdf:type/rdfs:subClassOf* brick:Power_Meter .
    ?light rdf:type/rdfs:subClassOf* brick:Light .
    ?room  rdf:type/rdfs:subClassOf* brick:Room .
    ?meter bf:feeds*/bf:isPointOf ?light .
    ?light (bf:isPartOf|bf:isLocatedIn)+ ?room .
    
    ?room bd:hasProperty ?max_occupants .
    ?max_occupants bd:hasData ?point .
    ?point bd:hasArchiver ?archiver .
    
    ?max_occupants rdf:type bdptl:MaxOccupantsProperty .
    
    ?point bd:uuid ?uuid .
    ?point bd:key  ?key .
    
    ?archiver bd:query   ?query .
    ?archiver bd:version ?version .
}

