SELECT DISTINCT ?meter ?room ?uuid ?key ?query ?version
WHERE {
    ?meter rdf:type/rdfs:subClassOf* brick:Power_Meter .
    ?light rdf:type/rdfs:subClassOf* brick:Light .
    ?room  rdf:type/rdfs:subClassOf* brick:Room .
    ?meter bf:feeds*/bf:isPointOf ?light .
    ?light (bf:isPartOf|bf:isLocatedIn)+ ?room .
    
    ?room bdptl:hasPropertyMaxOccupants ?max_occupants .
    ?max_occupants bdsmap:hasData ?point .
    ?point bdsmap:hasArchiver ?archiver .
    
    ?point bdsmap:uuid ?uuid .
    ?point bdsmap:key  ?key .
    
    ?archiver bdsmap:query   ?query .
    ?archiver bdsmap:version ?version .
}

