#!/usr/bin/env python

from os import listdir
import json
from time import time
import rdflib

buildingdir = 'buildings'
querydir = 'queries'
outputfilename = 'results.json'
blacklist_suite = [
    'solar',
    'lighting',
]
blacklist_building = [
#    'buildings/gth.ttl',
    'buildings/ou44.ttl',
]
blacklist_qpath = [
#    'queries/lighting-consumption.rq',
#    'queries/lighting-threshold-read.rq',
#    'queries/lighting-threshold-write.rq',
]

BRICKFRAME = rdflib.Namespace('http://buildsys.org/ontologies/BrickFrame#')

def load_buildings ():
    r = []
    
    for filename in listdir(buildingdir):
        if not filename.endswith('.ttl'):
            continue
        
        path = '%s/%s' % (buildingdir, filename)
        name = filename.split('.')[0]
        model = rdflib.Graph()
        model.parse(path, format='turtle')
        
        
        # inject inverse relationships
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasPart ?b . }"):
            model.add((row[1], BRICKFRAME.isPartOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isPartOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasPart, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasPoint ?b . }"):
            model.add((row[1], BRICKFRAME.isPointOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isPointOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasPoint, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:feeds ?b . }"):
            model.add((row[1], BRICKFRAME.isFedBy, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isFedBy ?b . }"):
            model.add((row[1], BRICKFRAME.feeds, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:controls ?b . }"):
            model.add((row[1], BRICKFRAME.isControlledBy, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isControlledBy ?b . }"):
            model.add((row[1], BRICKFRAME.controls, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:contains ?b . }"):
            model.add((row[1], BRICKFRAME.isLocatedIn, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isPartOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasPart, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasOutput ?b . }"):
            model.add((row[1], BRICKFRAME.isOutputOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isOutputOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasOutput, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasInput ?b . }"):
            model.add((row[1], BRICKFRAME.isInputOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isInputOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasInput, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasTagSet ?b . }"):
            model.add((row[1], BRICKFRAME.isTagSetOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isTagSetOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasTagSet, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:hasToken ?b . }"):
            model.add((row[1], BRICKFRAME.isTokenOf, row[0]))
        for row in model.query("SELECT ?a ?b WHERE { ?a bf:isTokenOf ?b . }"):
            model.add((row[1], BRICKFRAME.hasToken, row[0]))
        
        r.append({
            'path':  path,
            'id':    name,
            'model': model,
        })
    
    return r

def load_tests ():
    r = []
    
    for filename in listdir(querydir):
        if not filename.endswith('.rq'):
            continue
        
        path = '%s/%s' % (querydir, filename)
        suite = filename.split('-')[0]
        with open(path) as fo:
            query = ''.join(fo.readlines())
        
        r.append({
            'path':  path,
            'suite': suite,
            'test':  filename[len(suite)+1:-3],
            'query': query,
        })
    
    return r

# init
buildings = load_buildings()
tests     = load_tests()
results   = {}

# iteration
for i in range(1):
    for test in tests:
        for building in buildings:
            suite = test['suite']
            testcase = test['test']
            qpath = test['path']
            bid   = building['id']
            
            # perform blacklisting
            if building['path'] in blacklist_building:
                continue
            if qpath in blacklist_qpath:
                continue
            if suite in blacklist_suite:
                continue
            
            # perform test
            t0 = time()
            r = building['model'].query(test['query'])
            dt = time() - t0
#            resultcount = len(list(r))
            resultcount = list(r)
            
            # log result
            if not suite in results: results[suite] = {}
            if not testcase in results[suite]: results[suite][testcase] = {}
            if not bid in results[suite][testcase]: results[suite][testcase][bid] = []
            results[suite][testcase][bid].append({
                't0': t0,
                'dt': dt,
                'results': resultcount,
                'building': building['path'],
                'query': test['path'],
            })
    
    if i % 100 == 0:
        print('Done with iteration %u. Dumping to %s' % (i, outputfilename))
        
        with open(outputfilename, 'w') as fo:
            dump = json.dumps(results, sort_keys=True, indent=4, separators=(',', ': '))
            fo.writelines(dump)
            print('written (%s|%s) to %s' % (type(dump), len(dump), outputfilename))
#            print(results)

