#!/usr/bin/env python3.5

import sys
import rdflib

# guard: commandline arguments
if len(sys.argv) != 3:
    print('Syntax: %s INPUT_FILENAME OUTPUT_FILENAME' % sys.argv[0])
    print('        %s ../../GroundTruth/building_instances/gtc_brick.ttl gth.ttl' % sys.argv[0])
    exit()
ifilename = sys.argv[1]
ofilename = sys.argv[2]

# load input
g = rdflib.Graph()
g.parse(ifilename, format='turtle')
initial_relation_count = len(g)

# load extension
g.parse('brick-data.ttl', format='turtle')

# write output
print('Number of new relations: %u' % (len(g)-initial_relation_count))
g.serialize(ofilename, 'turtle')

